name: Update DNS Records

on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-dns:
    runs-on: ubuntu-22.04
    permissions:
      contents: write  # 添加写入权限
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Create ip directory
      run: |
        mkdir -p ip
        touch ip/.gitkeep
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Prepare CloudflareST directory
      run: mkdir -p speedtest

    - name: Download CloudflareST
      run: |
        if [ ! -f "speedtest/CloudflareST" ]; then
          echo "CloudflareST not found, downloading..."
          wget -O CloudflareST.tar.gz https://github.com/XIU2/CloudflareSpeedTest/releases/download/v2.2.4/CloudflareST_linux_amd64.tar.gz
          tar -zxf CloudflareST.tar.gz -C speedtest
          chmod +x speedtest/CloudflareST
          rm CloudflareST.tar.gz
        else
          echo "CloudflareST already exists, skipping download"
        fi
        
    - name: Run update script
      run: python update_dns.py
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        CF_ZONE_ID: ${{ secrets.CF_ZONE_ID }}
        CF_BASE_DOMAIN: ${{ secrets.CF_BASE_DOMAIN }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_URL_REGIONS: ${{ secrets.API_URL_REGIONS }}
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        
    - name: Commit ip directory
      run: |
        # 如果ip目录中有其他文件,则删除.gitkeep
        if [ "$(ls -A ip/)" != ".gitkeep" ]; then
          rm -f ip/.gitkeep
        fi
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ip/
        git commit -m "Update IP files" || echo "No changes to commit"
        git push
